version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: time_tracker_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: time_tracker
    ports:
      - "15432:5432"
    volumes:
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    tty: true
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    container_name: time_tracker
    ports:
      - '8181:8080'
    environment:
      - DB_URL=jdbc:postgresql://db:5432/time_tracker
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - db